# -------------------------------------------------------------------------------------
#
# Copyright (c) 2023, WSO2 LLC. (http://www.wso2.com). All Rights Reserved.
#
# This software is the property of WSO2 LLC. and its suppliers, if any.
# Dissemination of any information or reproduction of any material contained
# herein in any form is strictly forbidden, unless permitted by WSO2 expressly.
# You may not alter or remove any copyright or other notice from copies of this content.
#
# --------------------------------------------------------------------------------------

variable "alert_name" {
  description = "Short name segment used in the alert policy display name"
  type        = string
}

variable "project_id" {
  description = "The ID of the project in which the alert policy will be created. Defaults to the provider project if not set"
  type        = string
}

variable "combiner" {
  description = "How to combine results when multiple conditions are specified. Valid values: AND, OR, AND_WITH_MATCHING_RESOURCE (default: OR)"
  type        = string
  default     = "OR"
}

variable "enabled" {
  description = "Whether the alert policy is enabled. Defaults to true"
  type        = bool
  default     = true
}

variable "severity" {
  description = "Severity of incidents generated by this policy. Valid values: CRITICAL, ERROR, WARNING"
  type        = string
  default     = null
}

variable "notification_channels" {
  description = "List of notification channel resource names to alert on incident open/close. Format: projects/[PROJECT_ID]/notificationChannels/[CHANNEL_ID]"
  type        = list(string)
  default     = []
}

variable "user_labels" {
  description = "Labels to attach to the alert policy. Keys and values must be lowercase letters, digits, underscores, or dashes; keys must start with a letter. Up to 64 entries"
  type        = map(string)
  default     = {}
}

variable "deletion_policy" {
  description = "Policy for handling the alert policy resource when the Terraform resource is destroyed. Valid values: DELETE (default) - deletes the alert policy; PREVENT - prevents Terraform from destroying the alert policy; ABANDON - removes the alert policy from Terraform management but leaves it in place"
  type        = string
  default     = "DELETE"
}

# ─── Conditions ───────────────────────────────────────────────────────────────
# A policy must have 1–6 conditions. Each condition block must contain exactly
# one of the following condition types:
#   condition_threshold                - Metric threshold comparison
#   condition_absent                   - Missing data detection
#   condition_monitoring_query_language - MQL boolean stream
#   condition_matched_log              - Log-based matching (cannot be combined with other conditions)
#   condition_prometheus_query_language - PromQL expression
#   condition_sql                      - GoogleSQL query (incurs additional billing)
#
# aggregations within condition_threshold / condition_absent:
#   per_series_aligner   - e.g. ALIGN_RATE, ALIGN_MEAN, ALIGN_DELTA (see provider docs for full list)
#   cross_series_reducer - e.g. REDUCE_SUM, REDUCE_MEAN, REDUCE_COUNT (see provider docs for full list)

variable "conditions" {
  description = "List of 1-6 alert conditions. Each must specify display_name and exactly one condition type block"
  type = list(object({
    display_name = string

    condition_threshold = optional(object({
      comparison              = string
      duration                = string
      filter                  = optional(string)
      threshold_value         = optional(number)
      denominator_filter      = optional(string)
      evaluation_missing_data = optional(string) # EVALUATION_MISSING_DATA_INACTIVE | EVALUATION_MISSING_DATA_ACTIVE | EVALUATION_MISSING_DATA_NO_OP

      aggregations = optional(list(object({
        alignment_period     = optional(string)
        per_series_aligner   = optional(string)
        cross_series_reducer = optional(string)
        group_by_fields      = optional(list(string), [])
      })), [])

      denominator_aggregations = optional(list(object({
        alignment_period     = optional(string)
        per_series_aligner   = optional(string)
        cross_series_reducer = optional(string)
        group_by_fields      = optional(list(string), [])
      })), [])

      forecast_options = optional(object({
        forecast_horizon = string
      }))

      trigger = optional(object({
        count   = optional(number)
        percent = optional(number)
      }))
    }))

    condition_absent = optional(object({
      duration = string
      filter   = optional(string)

      aggregations = optional(list(object({
        alignment_period     = optional(string)
        per_series_aligner   = optional(string)
        cross_series_reducer = optional(string)
        group_by_fields      = optional(list(string), [])
      })), [])

      trigger = optional(object({
        count   = optional(number)
        percent = optional(number)
      }))
    }))

    condition_monitoring_query_language = optional(object({
      query                   = string
      duration                = string
      evaluation_missing_data = optional(string) # EVALUATION_MISSING_DATA_INACTIVE | EVALUATION_MISSING_DATA_ACTIVE | EVALUATION_MISSING_DATA_NO_OP

      trigger = optional(object({
        count   = optional(number)
        percent = optional(number)
      }))
    }))

    condition_matched_log = optional(object({
      filter           = string
      label_extractors = optional(map(string), {})
    }))

    condition_prometheus_query_language = optional(object({
      query                     = string
      duration                  = optional(string)
      evaluation_interval       = optional(string)
      labels                    = optional(map(string), {})
      rule_group                = optional(string)
      alert_rule                = optional(string)
      disable_metric_validation = optional(bool)
    }))

    condition_sql = optional(object({
      query = string

      # Exactly one of minutes / hourly / daily must be set
      minutes = optional(object({
        periodicity = number # 5–1440
      }))

      hourly = optional(object({
        periodicity   = number          # 1–48
        minute_offset = optional(number) # 0–59
      }))

      daily = optional(object({
        periodicity = number # 1–30
        execution_time = optional(object({
          hours   = optional(number)
          minutes = optional(number)
          seconds = optional(number)
          nanos   = optional(number)
        }))
      }))

      # Exactly one of row_count_test / boolean_test must be set
      row_count_test = optional(object({
        comparison = string # COMPARISON_GT | COMPARISON_GE | COMPARISON_LT | COMPARISON_LE | COMPARISON_EQ | COMPARISON_NE
        threshold  = string
      }))

      boolean_test = optional(object({
        column = string
      }))
    }))
  }))
}

variable "documentation" {
  description = "Documentation content to include in the alert policy"
  type = optional(object({
    content   = optional(string)
    mime_type = optional(string, "text/markdown")
    subject   = optional(string)

    links = optional(list(object({
      display_name = optional(string)
      url          = optional(string)
    })), [])
  }))
  default = null
}

variable "alert_strategy" {
  description = "Strategy for alerting when incidents are opened or closed. If not specified, a default strategy with no auto-close and no notification rate limit will be used."
  type = optional(object({
    auto_close           = optional(string)
    notification_prompts = optional(list(string), [])

    notification_rate_limit = optional(object({
      period = optional(string)
    }))

    notification_channel_strategy = optional(list(object({
      notification_channel_names = optional(list(string), [])
      renotify_interval          = optional(string)
    })), [])
  }))
  default = null
}
